### ISSUE TITLE
Insult Lexicon

### ISSUE THREAD

**Issue by gao00061** [DUT-lujunyu/ToxiCN#2]
Dear Junyu,

Thank you so much for your great work in Chinese toxic language detection.

We are doing a related work that need to find proper lexicon to do some detection, therefore, I am wondering if you are going to upload the lexicon soon.

Thanks again.

**Comment by DUT-lujunyu** [comment]
Thank you for your interest in our work and we apologize for the delayed response. 

We have actually made available a subset of our lexicon at https://github.com/DUT-lujunyu/ToxiCN/tree/main/ToxiCN_ex/ToxiCN/lexicon, which encompasses high frequency words. We aim to compile more words and develop corresponding regular expressions at our earliest convenience. 

We hope this information proves to be useful to you.
