### ISSUE TITLE
src.helper模块

### ISSUE THREAD

**Issue by cccjjjfff6** [DUT-lujunyu/ToxiCN#4]
请问src.helper模块能否上传

**Comment by DUT-lujunyu** [comment]
感谢提醒，我们注意到 src.helper 和调用它的代码 src/urils.py 都是误加到项目中的，现已删除。
如果您想阅读 src.helper 的原始代码，可以查看 https://github.com/DUT-lujunyu/MHCAN/blob/main/src/helper.py

**Comment by cccjjjfff6** [comment]
> 感谢提醒，我们注意到 src.helper 和调用它的代码 src/urils.py 都是误加到项目中的，现已删除。 如果您想阅读 src.helper 的原始代码，可以查看 https://github.com/DUT-lujunyu/MHCAN/blob/main/src/helper.py

谢谢
